version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.1-browsers
        environment:
          RAILS_ENV: test
          HUKAIDONG_COM_DATABASE_HOST: localhost
          HUKAIDONG_COM_DATABASE_PASSWORD: hukaidong_com

      - image: cimg/postgres:12.14
        environment:
          POSTGRES_USER: hukaidong_com
          POSTGRES_PASSWORD: hukaidong_com
          POSTGRES_DB: hukaidong_com_test

    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.2.3
            bundle install
            bundle exec rake test:all
